name: 'Setup Windows Environment'
description: 'Configure Windows-specific settings for long paths and short cargo paths'

runs:
  using: "composite"
  steps:
    - name: Enable long paths (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git config --global core.longpaths true
        git config --global core.autocrlf input
        git config --global core.eol lf
        New-ItemProperty `
          -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" `
          -Name "LongPathsEnabled" `
          -Value 1 `
          -PropertyType DWORD `
          -Force `
          | Out-Null
        "CARGO_HOME=C:\\c" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "RUSTUP_HOME=C:\\r" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "CARGO_TARGET_DIR=C:\\t" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
